name: Android CI (APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platforms;android-33" "platform-tools" "build-tools;33.0.1"
          yes | sdkmanager --licenses

      # If gradlew is missing, download Gradle 8.2 and generate the wrapper
      - name: Bootstrap Gradle wrapper when missing
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found — bootstrapping wrapper with Gradle 8.2"
            curl -L -o gradle-8.2-bin.zip https://services.gradle.org/distributions/gradle-8.2-bin.zip
            unzip -q gradle-8.2-bin.zip -d $HOME
            $HOME/gradle-8.2/bin/gradle --version
            $HOME/gradle-8.2/bin/gradle wrapper --gradle-version 8.2
          fi
          chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
        env:
          # If your app calls OpenAI directly from the client (not recommended),
          # you can forward a value during CI for tests. For runtime on device,
          # the key must be provided by your app or backend.
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SalesMaster-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
