name: Android CI (APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_DIR: .

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 8.x
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platforms;android-33" "platform-tools" "build-tools;33.0.1"
          yes | sdkmanager --licenses

      # Only chmod if gradlew exists
      - name: Make gradlew executable
        run: if [ -f gradlew ]; then chmod +x gradlew; fi

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: SalesMaster-debug-apk
          path: ${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/app-debug.apk
